version: '3.7'

services:
  auditbeat:
    build:
      context: extensions/auditbeat-server/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: auditbeat
    hostname: auditbeat
    command: auditbeat -e -strict.perms=false
    user: root #To read the docker socket
    environment:
      - setup.kibana.host=kibana:5601
    cap_add: ['AUDIT_CONTROL', 'AUDIT_READ']
    pid: "host" # Set the required permissions with pid and cap_add for Auditbeat
    volumes:
      - certs:$CERTS_DIR
      - ./extensions/auditbeat-server/config/auditbeat.docker.yml:/usr/share/auditbeat/auditbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk
    depends_on:
      - elasticsearch
