version: '2.2'
#docker-compose -f create-certs.yml run --rm create_certs
services:
  create_certs:
    container_name: create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELK_VERSION
    command: >
      bash -c '
        yum install -y -q -e 0 unzip;
        rm -rf /certs/bundle.zip;
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
          unzip -o /certs/bundle.zip -d /certs; 
        fi;
        chown -R 1000:0 /certs;
         ls -l /certs;
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: ['certs:/certs', '.:/usr/share/elasticsearch/config/certificates']
    environment:
      - network.host=_eth0_    
    networks:
      - elk
      
networks:
  elk:

volumes: {"certs"}