---
# Remember, leave a key empty if there is no value. None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - ${ELASTICSEARCH_HOST}
  port: 9200
  url_prefix:
  use_ssl: True
  certificate: /usr/share/elasticsearch/config/certificates/ca/ca.crt
  client_cert: /usr/share/elasticsearch/config/certificates/curator/curator.crt
  client_key: /usr/share/elasticsearch/config/certificates/curator/curator.key
  ssl_no_validate: True
  #http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: DEBUG
  logfile:
  logformat: default
