apm-server:
  host: 0.0.0.0:8200

output:
  elasticsearch:
    hosts: ['https://elasticsearch:9200']
    username: elastic
    password: changeme

    ssl.certificate_authorities: ["/usr/share/elasticsearch/config/certificates/ca/ca.crt"]
    ssl.certificate: "/usr/share/elasticsearch/config/certificates/auditbeat/auditbeat.crt"
    ssl.key: "/usr/share/elasticsearch/config/certificates/auditbeat/auditbeat.key"